### PR TITLE
build: bump deps

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by thi4go** [comment]
Hey dhill, gave this PR a go but something is off, got an error from pi-ui when trying to run the app on my browser.

**Review by thi4go — CHANGES_REQUESTED** [review]
Getting the following error when running the app with this PR:
image

Any ideas @tiagoalvesdulce? Will try to open a fresh PR bumping the deps and removing unused ones soon

**Review by tiagoalvesdulce — CHANGES_REQUESTED** [review]
Reviewing this more closely I noticed that it uses a legacy approach to pi-ui themes here:  https://github.com/decred/dcrtimegui/blob/0cb2df817b23be137fd631e84f61b6b3d8542029/src/App.js#L7 but we introduce `ThemeProvider` here: https://github.com/decred/pi-ui/pull/191. To bump pi-ui version we have to wrap the App component with a `ThemeProvider`

**Comment by tiagoalvesdulce** [comment]
@thi4go should be good now. Can you give it a try?

**Review by thi4go — APPROVED** [review]
Yep working great, thanks @tiagoalvesdulce

**Comment by tiagoalvesdulce** [comment]
Great!

**Review by tiagoalvesdulce — APPROVED** [review]

**Pull request merged**
