### PR TITLE
[redesign][wip] Remove inline styles

### LINKED ISSUE #84: CSP Remove inline styles
See https://github.com/decred/dcrtimegui/pull/83

We had to use "unsafe-inline" for the style-src . Obviously "unsafe-inline" is an **unsafe** setting. 

We should aim to remove all the inline styles from the webapp so that we can use a more secure CSP header.

### PR DESCRIPTION
**Pull request by amassarwi**
This PR tracks the progress of removing all inline styles, which also means we'll need to migrate from using the styled-components library and use css files & `pi-ui` when needed.

**Based on:** #89 
Closes #84

### CODE REVIEW

**Comment by fernandoabolafio** [comment]
@amassarwi since we're migrating from styled-components I think we should keep the style used on politeiagui where each component has its own CSS file. So instead of doing `components.modules.css`  break it down per component usage (e.g TimestampForm.module.css, Expandable.module.css, etc). Otherwise, it will be the same as using a single giant stylesheet which we want to avoid.

**Comment by tiagoalvesdulce** [comment]
@amassarwi are you still working on this?

**Comment by amassarwi** [comment]
@fernandoabolafio I've already discussed it with @thi4go, this was my first approach, but @thi4go suggested to go with one file for now break to separated files if it grows to big.

@tiagoalvesdulce Yes I'm, but we decided to wait with it tell we merge the two prs @thi4go opened before I could continue with this one, in order to avoid the conflicts.

**Comment by amassarwi** [comment]
@tiagoalvesdulce so basically this waiting for #91 & #92

**Comment by tiagoalvesdulce** [comment]
OK, cool. I agree with @fernandoabolafio about the CSS. There's no reason to use CSS Modules if we keep a giant CSS file, it also makes reviews more difficult and increases code conflicts. Why do you think we should keep a single CSS file @thi4go?

**Comment by thi4go** [comment]
@tiagoalvesdulce some components have very few classes, so my idea was to migrate to a separte css module if it growed bigger. Reading through the comments, I agree that it doesn't match with the idea of modules, so I'll be migrating the each component css to its own module on #91. Is that ok?

**Comment by amassarwi** [comment]
Will be done as part of the refactoring by @thi4go

**Pull request closed without merging**
